version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/dev.db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here-change-in-production
      - JWT_SECRET=your-jwt-secret-here-change-in-production
    volumes:
      - ./dev.db:/app/dev.db
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: alpine:latest
    volumes:
      - ./dev.db:/app/dev.db
    command: sh -c "touch /app/dev.db && chown 1000:1000 /app/dev.db"

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
